apiVersion: v1
kind: Secret
metadata:
  name: operations-service-secrets
  namespace: operations-service
  labels:
    app: operations-service
type: Opaque
stringData:
  # Preencha com os valores reais antes de aplicar
  DB_HOST: "postgres:5432"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  JWT_SECRET: "CHANGE_ME_BASE64_OR_PLAIN"
  NEW_RELIC_LICENSE_KEY: "CHANGE_ME"
