apiVersion: v1
kind: Service
metadata:
  name: oficina-operations-service
  namespace: oficina
  annotations:
    # Use NLB (recommended for TCP performance) or remove for Classic/ALB default
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
