apiVersion: v1
kind: ServiceAccount
metadata:
  name: oficina-sa
  namespace: oficina
imagePullSecrets:
  # Name of the docker-registry secret (create with kubectl). Example: 'regcred'
  - name: regcred
